server:
  port: 9001
  servlet:
    context-path: /nacos-provider/
spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: 10.1.11.159:80

management:
  endpoint:
    web:
      exposure:
        include:'*'