server:
  port: 9002
#  servlet:
#    context-path: /panpan/    #/nacos-provider/
spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
      server-addr: 10.1.11.159:8848

management:
  endpoint:
    web:
      exposure:
        include:'*'