server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.1.11.159:80
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes: # 路由
        - id: nacos-provider #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: http://10.1.11.159:9001/nacos-provider # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/nacos-provider/** # 断言，路径相匹配进行路由
          #https://localhost:9999/nacos-provider/panpan
          #http://10.1.11.159:9001/nacos-provider/panpan

management:
  endpoint:
    web:
      exposure:
        include:'*'