server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.1.11.159:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心的路由
      routes:
        - id: nacos-provider  #路由ID,没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://nacos-provider #路由到注册中心服务为nacos-provider 的服务 匹配提供服务的路由
          predicates: #断言
            - Path=/panpan/** #断言，路径相匹配进行路由
#            - After=2024-10-29T21:40:10.529+08:00[Asia/Shanghai]
#            - Cookie=username,[a-z]+ # 匹配Cookie的key和value（正则表达式）
#            - Header=X-Request-Id,\d+ #表示数字
#            - Host=**.mashibing.com #匹配当前的主机地址发出的请求
#            - Method=GET,POST # 匹配GET请求或者POST请求
          filters:
            - StripPrefix=1
#    gateway:
#      discovery:
#        locator:
#          enabled: true #开启注册中心路由功能
#      routes: # 路由
#        - id: nacos-provider #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
#          uri: http://10.1.11.159:9001/nacos-provider # 匹配提供服务的路由地址
#          predicates: # 断言
#            - Path=/nacos-provider/** # 断言，路径相匹配进行路由
#          #https://localhost:9999/nacos-provider/panpan
#          #http://10.1.11.159:9001/nacos-provider/panpan

management:
  endpoint:
    web:
      exposure:
        include:'*'