# DataSource Config
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/mybatis-plus?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  type-aliases-package: com.panpan.mybatisplus.entity
  mapper-locations: classpath:mapper/**.xml

  # 指定日志输出
mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
# 配置MyBatis-Plus操作表的默认前缀
#  global-config:
#    db-config:
#      table-prefix:
#        t_


